# -*- coding: utf-8 -*-
"""language translator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTfMTC05BZL-rK6-W7Gqu_5FgH-nnF7Y
"""

!pip install torch==2.3.0 torchvision==0.18.0 torchaudio===2.3.0 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

!pip install transformers ipywidgets gradio --upgrade

import gradio as gr
from transformers import pipeline

translation_pipeline = pipeline('translation_en_to_de')

results = translation_pipeline('I love Icecream')

results[0]['translation_text']

def translate_transformers(from_text):
  results = translation_pipeline(from_text)
  return results[0]['translation_text']

translate_transformers('go there and sit')

!pip install gradio==3.43.1

interface = gr.Interface(fn=translate_transformers,
                         inputs=gr.Textbox(),
                         outputs=gr.Textbox())

!pip install --upgrade gradio

interface.launch()

